name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2.8', '3.3.0']
        rails-version: ['7.0', '7.1', '8.0']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install Rails
        run: |
          gem install rails -v "~> ${{ matrix.rails-version }}.0"
      - name: Run all tests with coverage
        run: bundle exec rspec
        env:
          COVERAGE: true
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          RAILS_VERSION: ${{ matrix.rails-version }}
      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report-ruby-${{ matrix.ruby-version }}-rails-${{ matrix.rails-version }}
          path: coverage
          retention-days: 14

  example-integration:
    name: Example App Integration Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2.8', '3.3.0']
        rails-version: ['7.0', '7.1', '8.0']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install Rails
        run: |
          gem install rails -v "~> ${{ matrix.rails-version }}.0"
      - name: Run example app tests
        run: |
          cd example
          bundle install
          bundle exec rspec

  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true
      
      - name: Run RuboCop on main gem
        run: bundle exec rubocop
        
      - name: Run RuboCop on example app
        run: |
          cd example
          bundle install
          bundle exec rubocop --ignore-parent-exclusion 